version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-backend
    restart: unless-stopped
    env_file: .env.production
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi-db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db
    networks:
      - strapi

  strapi-db:
    image: postgres:15-alpine
    container_name: strapi-postgres
    restart: unless-stopped
    env_file: .env.production
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - strapi-data:/var/lib/postgresql/data
    networks:
      - strapi

  nginx:
    image: nginx:alpine
    container_name: strapi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/ssl:/etc/ssl/certs
    depends_on:
      - strapi
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: strapi 