version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development  # 使用development以保持与开发环境一致
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      HOST: 0.0.0.0
      PORT: 1337
      # 生产环境请修改这些密钥
      JWT_SECRET: your-jwt-secret-change-me
      ADMIN_JWT_SECRET: your-admin-jwt-secret-change-me
      APP_KEYS: key1,key2,key3,key4
      API_TOKEN_SALT: your-api-token-salt
      TRANSFER_TOKEN_SALT: your-transfer-token-salt
      # API配置（如果需要translate功能）
      STRAPI_API_TOKEN: your-strapi-api-token
      STRAPI_BASE_URL: http://localhost:1337
      DEEPL_AUTH_KEY: your-deepl-api-key
    volumes:
      # 持久化数据库 - 双向同步，允许在容器和主机间共享数据
      - ./.tmp:/app/.tmp
      # 持久化上传文件
      - ./public/uploads:/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1337", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  strapi-network:
    driver: bridge 